### PR TITLE
Add cautious-robot logo

### PR DESCRIPTION
**Pull request by egrace479**
Adds AI-generated cautious-robot logo to the README. Set it at 500px so it won't be too large on the screen.

### CODE REVIEW

**Review by thompsonmj — APPROVED** [review]
Cute lil guy

**Comment by hlapp** [comment]
Any reason you wouldn't put the logo image into the repo? Also, I would right-float the image. (And you can still put the image at full rez and then resize for display.)

**Comment by egrace479** [comment]
> Any reason you wouldn't put the logo image into the repo? Also, I would right-float the image. (And you can still put the image at full rez and then resize for display.)

When I fixed the height, the aspect ratio doesn't resize under 500px (width will be narrower but height stays fixed). I didn't put it in directly so it'd be visible, but I can adjust both.

Curious, why right float? And do you think 500px is a good fixed size?

**Comment by hlapp** [comment]
> Curious, why right float? And do you think 500px is a good fixed size?

Without the float, you have this relatively large vertical space that one needs to scroll over without learning anything new. With float, you can have both the logo and the text side-by-side, so the logo artfully embellishes but does not take over the space.

As for the size, 500px is a bit large, and would be especially so on a mobile device. Personally I would instead use relative width (then height will be automatic).

**Comment by egrace479** [comment]
> > Curious, why right float? And do you think 500px is a good fixed size?
> 
> Without the float, you have this relatively large vertical space that one needs to scroll over without learning anything new. With float, you can have both the logo and the text side-by-side, so the logo artfully embellishes but does not take over the space.

Ahh I misunderstood! Yes, definitely a good idea!

> As for the size, 500px is a bit large, and would be especially so on a mobile device. Personally I would instead use relative width (then height will be automatic).

Sounds good.

**Comment by egrace479** [comment]
Thanks, @hlapp! That was the style fix I needed :)

**Pull request merged**
